name: frontend
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.2
  image_picker: ^1.1.2



  uuid: ^3.0.6

  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.0.6
  

  cupertino_icons: ^1.0.8
  flutter_login: ^5.0.0

  collection: ^1.18.0
  flutter_lints: ^5.0.0
  http_parser: ^4.0.2
  js: ^0.6.7
  matcher: ^0.12.16
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path: ^1.8.3
  phone_numbers_parser: ^8.3.0
  stack_trace: ^1.11.1
  string_scanner: ^1.2.0
  test_api: ^0.7.2
  url_launcher_android: ^6.3.2
  url_launcher_ios: ^6.2.4
  url_launcher_linux: ^3.1.1
  url_launcher_macos: ^3.2.0
  url_launcher_web: ^2.2.3
  web: ^1.1.0
  provider: ^6.1.2
  dio: ^5.7.0
  font_awesome_flutter: ^10.8.0
  universal_platform: ^1.1.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
